<?php

/**
 * Generated by ZF2ModuleCreator
 */

/** @noinspection SenselessCommaInArrayDefinitionInspection */
/** @noinspection SenselessCommaInArrayDefinitionInspection */
return [

    'view_manager' => [
        'template_path_stack' => [
            __DIR__ . '/../view',
        ],
    ],

    'controllers' => [

    ],

    'service_manager' => [

    ],

    'router' => [
// Uncomment below to add routes
//        'routes' => array(
//            'user' => array(
//                'type' => 'Literal',
//                'options' => array(
//                    'route' => '/user',
//                    'defaults' => array(
//                        '__NAMESPACE__' => 'user\Controller',
//                        'controller' => 'user',
//                        'action' => 'index',
//                    )
//                )
//            )
//        ),
//        'may_terminate' => true,
//        'child_routes' => array(
//            'default' => array(
//                'type' => 'Segment',
//                'options' => array(
//                    'route' => '/[:controller[/:action]]',
//                    'constraints' => array(
//                        'controller' => '[a-zA-Z][a-zA-Z0-9_-]*',
//                        'action' => '[a-zA-Z][a-zA-Z0-9_-]*',
//                    )
//                )
//            )
//        )
    ]
];